# note that environment variables are automatically imported from `.env` when running `docker-compose up`
version: '3'
services:
  # reverse-proxy:

  web-server:
    restart: always
    build: 
      context: ./web-server
      dockerfile: ./Dockerfile
    expose: 
      - ${SERVER_LISTEN_PORT}
    depends_on:
      - database

  database:
    image: postgres
    volumes:
      # mounting db file outside the container so it persists:
      # - "./database/postgres_database:/var/lib/mysql"
      # init script to create tables:
      - "./database/create_table_statements.sql:/docker-entrypoint-initdb.d/create_table_statements.sql"
    expose:
      - ${DATABASE_PORT}
    environment:
      POSTGRES_ROOT_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
