version: '3'
services:
  # reverse-proxy:

  web-server:
    restart: always
    build: 
      context: ./web-server
      dockerfile: ./Dockerfile
    expose: 
      - ${SERVER_LISTEN_PORT}
    depends_on:
      - database

  database:
    image: postgres
    expose:
      - ${DATABASE_PORT}
    environment:
      POSTGRES_ROOT_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
